"""
Central configuration for the GenAI Financial Earnings Report Analyst.

All tunable parameters, file paths, API settings and constants live here so
that no other module hard-codes configuration values. Settings are loaded from
environment variables (via a local ``.env`` file) where appropriate, with safe
defaults for everything else.

Sprint 1 scope: configuration for ingestion, the RAG subsystem and the Llama 3
language model. Steps 9-12 (KPI comparison, charts, PDF, full dashboard) are
Sprint 2 deliverables.
"""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

# --------------------------------------------------------------------------- #
# Environment
# --------------------------------------------------------------------------- #
# Load variables from a local .env file if present (never committed to git).
load_dotenv()

# --------------------------------------------------------------------------- #
# Project paths
# --------------------------------------------------------------------------- #
# Resolve the project root (three levels up from this file:
# core -> genai_analyst -> src -> <project root>).
PROJECT_ROOT: Path = Path(__file__).resolve().parents[3]
DATA_DIR: Path = PROJECT_ROOT / "data"
CACHE_DIR: Path = DATA_DIR / "cache"
CHROMA_DIR: Path = DATA_DIR / "chroma"

# Ensure runtime directories exist.
for _directory in (DATA_DIR, CACHE_DIR, CHROMA_DIR):
    _directory.mkdir(parents=True, exist_ok=True)

# --------------------------------------------------------------------------- #
# SEC EDGAR settings
# --------------------------------------------------------------------------- #
# The SEC requires a descriptive User-Agent for all programmatic requests.
SEC_USER_AGENT: str = os.getenv(
    "SEC_USER_AGENT", "GenAI Earnings Analyst contact@example.com"
)
SEC_COMPANY_TICKERS_URL: str = "https://www.sec.gov/files/company_tickers.json"
SEC_SUBMISSIONS_URL: str = "https://data.sec.gov/submissions/CIK{cik10}.json"
SEC_ARCHIVES_URL: str = (
    "https://www.sec.gov/Archives/edgar/data/{cik}/{accession}/{doc}"
)

# HTTP resilience.
HTTP_MAX_RETRIES: int = 4
HTTP_BACKOFF_SECONDS: float = 1.5
HTTP_TIMEOUT_SECONDS: int = 30

# --------------------------------------------------------------------------- #
# RAG subsystem settings
# --------------------------------------------------------------------------- #
EMBEDDING_MODEL_NAME: str = "all-MiniLM-L6-v2"   # 384-dimensional embeddings
CHUNK_SIZE: int = 2500
CHUNK_OVERLAP: int = 250
RAG_TOP_K: int = 5

# --------------------------------------------------------------------------- #
# Llama 3 (LLM) settings
# --------------------------------------------------------------------------- #
# API key is read from the environment and must never be hard-coded.
LLAMA3_API_KEY: str = os.getenv("LLAMA3_API_KEY", "")
LLAMA3_BASE_URL: str = os.getenv(
    "LLAMA3_BASE_URL", "https://api.groq.com/openai/v1/chat/completions"
)
LLAMA3_MODEL: str = os.getenv("LLAMA3_MODEL", "llama-3.1-8b-instant")
LLAMA3_MAX_TOKENS: int = 500
LLAMA3_TEMPERATURE: float = 0.2

# --------------------------------------------------------------------------- #
# FinBERT settings
# --------------------------------------------------------------------------- #
FINBERT_MODEL_NAME: str = "ProsusAI/finbert"
FINBERT_MAX_CHUNKS: int = 40

# --------------------------------------------------------------------------- #
# Disclaimers / constants
# --------------------------------------------------------------------------- #
DISCLAIMER: str = (
    "This analysis is generated by an automated system for informational "
    "purposes only and does not constitute financial advice. All figures are "
    "sourced from official SEC filings; narrative text is AI-generated and may "
    "contain errors. Always verify against primary sources."
)


def is_llm_configured() -> bool:
    """Return True if a Llama 3 API key is available."""
    return bool(LLAMA3_API_KEY)
